server:
  servlet:
    session:
      tracking-modes: cookie
      timeout: 1200

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blogdb?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: jang6955
    driver-class-name: com.mysql.jdbc.Driver
  messages:
    basename: errors

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type : trace
